featured_tag:
  type: string
  default: "featured"
  description:
    en: "Tag used to select featured topics."

topic_count:
  type: integer
  default: 6
  min: 1
  max: 30
  description:
    en: "Maximum number of tagged topics to fetch and display."

slides_desktop:
  type: integer
  default: 3
  min: 1
  max: 6
  description:
    en: "Number of topic cards visible at desktop widths."

show_on:
  type: list
  list_type: enum
  default: "custom_homepage|latest"
  choices:
    "custom_homepage": "Custom homepage"
    "latest": "Latest"
    "top": "Top"
    "new": "New"
    "categories": "Categories"
    "tags": "Tag routes"
  description:
    en: "Routes where the slider should appear."

show_title:
  type: bool
  default: true
  description:
    en: "Show the component heading."

randomize_position:
  type: bool
  default: false
  description:
    en: "Place the slider at a random position inside the topic list."

title_text:
  type: string
  default: "Featured"
  description:
    en: "Heading text displayed above the slider."

hide_tag_chip:
  type: bool
  default: false
  description:
    en: "Hide the featured tag pill on topic cards."

include_pinned:
  type: bool
  default: false
  description:
    en: "Include pinned topics in the featured list."

shuffle_topics:
  type: bool
  default: false
  description:
    en: "Shuffle the fetched topics before rendering."

insert_mode:
  type: enum
  default: "after_n"
  choices:
    "before_list": "Before topic list"
    "before_navigation": "Before navigation controls"
    "after_n": "After Nth topic row"
    "list_footer": "After topic list"
  description:
    en: "Where to insert the slider relative to the topic list."

position_index:
  type: integer
  default: 5
  min: 1
  description:
    en: "List row index used when insert mode is after N and randomization is disabled."

random_min_index:
  type: integer
  default: 3
  min: 1
  description:
    en: "Minimum list row index when randomizing slider placement."

random_max_index:
  type: integer
  default: 10
  min: 1
  description:
    en: "Maximum list row index when randomizing slider placement."

autoplay:
  type: bool
  default: false
  description:
    en: "Automatically advance the slider at a set interval."

autoplay_interval_ms:
  type: integer
  default: 5000
  min: 1000
  description:
    en: "Autoplay interval in milliseconds."

card_aspect_ratio:
  type: enum
  default: "16:9"
  choices:
    "16:9": "16:9 (widescreen)"
    "3:2": "3:2"
    "4:3": "4:3"
  description:
    en: "Aspect ratio for the media area of each topic card."
